# This file defines setup of the experiment.


data:
    size: 500000
    n_items: 4

generator:
    z_dim: 1
    layer_sizes:
        - 3

discriminator:
    layer_sizes: []

optimization:
    n_epochs: 10
    batch_size: 64
    learning_rate: 0.00005
    beta_one: 0.5
